#### **Output**: matched, cleaned csv files in `workspace/longitudinal_data.csv` and `workspace/longitudinal_events.csv`

# Match data based on study date

In [5]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mcolors
from tqdm import tqdm as tqdm

In [45]:
DATA_DIR = "/storage/groups/ml01/datasets/projects/20181610_eyeclinic_niklas.koehler/joint_export"

RAW_DIR = "/storage/groups/ml01/datasets/raw/2018_LMUAugenklinik_niklas.koehler"

data_dir = os.path.join(RAW_DIR, 'joint_export/dwh_tables')

clean_data_dir = os.path.join(DATA_DIR, 'dwh_tables_cleaned')

In [46]:
os.listdir(clean_data_dir)

['icd10cm_codes_2018.txt',
 'procedures_clean.csv',
 'naive_patients.csv',
 'octs_fundus_no_dups.csv',
 'diagnosis.csv',
 'octs_fundus_with_dups.csv',
 'visus_labels_clean.csv',
 'diagnosis_longitudinal_clean.csv',
 'icd10cm_order_2018.txt']

In [56]:
octs = pd.read_csv(os.path.join(clean_data_dir, 'octs_fundus_no_dups.csv'), index_col=0)
octs.study_date = pd.to_datetime(octs.study_date, format="%Y%m%d")
octs.patient_id = octs.patient_id.astype(str)


visus = pd.read_csv(os.path.join(clean_data_dir, 'visus_labels_clean.csv'), index_col=0)
visus.study_date = pd.to_datetime(visus.study_date)
visus.patient_id = visus.patient_id.astype(int).astype(str)

injections = pd.read_csv(os.path.join(clean_data_dir, 'procedures_clean.csv'), index_col=0)
injections.study_date = pd.to_datetime(injections.study_date)
injections.patient_id = injections.patient_id.astype(str)

diagnosis = pd.read_csv(os.path.join(clean_data_dir, 'diagnosis_longitudinal_clean.csv'), index_col=0)
diagnosis = diagnosis.reset_index()
diagnosis.patient_id = diagnosis.patient_id.astype(str)

In [68]:
longitudinal_data

,patient_id,laterality,study_date,oct_path,fundus_path,laterality_raw_x,visual_acuity,logMAR,ICPMK,ICPML,laterality_raw_y,thickness_path,oct?,visus?,thickness?,fundus?,diagnosis,MED
0,34537,R,2014-12-16,/storage/groups/ml01/datasets/raw/2018_LMUAuge...,NaN,R,0.2,0.69897,NaN,NaN,NaN,NaN,True,True,False,False,AMD,NaN
1,34537,R,2016-01-26,/storage/groups/ml01/datasets/raw/2018_LMUAuge...,NaN,R,0.25,0.60206,NaN,NaN,NaN,NaN,True,True,False,False,AMD,NaN
2,34537,R,2017-12-13,/storage/groups/ml01/datasets/raw/2018_LMUAuge...,NaN,R,0.25,0.60206,NaN,NaN,NaN,NaN,True,True,False,False,AMD,NaN
3,34537,R,2014-09-16,/storage/groups/ml01/datasets/raw/2018_LMUAuge...,NaN,R,0.32,0.49485,NaN,NaN,NaN,NaN,True,True,False,False,AMD,NaN
4,34537,R,2013-11-05,/storage/groups/ml01/datasets/raw/2018_LMUAuge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,AMD,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68859,295960,R,2014-10-30,NaN,NaN,NaN,NaN,NaN,PC,5-133,R,NaN,False,False,False,False,AMD,NaN
68860,295960,R,2014-10-30,NaN,NaN,NaN,NaN,NaN,PC,5-142,R,NaN,False,False,False,False,AMD,NaN
68861,295960,R,2014-10-30,NaN,NaN,NaN,NaN,NaN,PC,5-147,R,NaN,False,False,False,False,AMD,NaN
68862,295960,R,2014-12-11,NaN,NaN,NaN,NaN,NaN,PC,5-156,R,NaN,False,False,False,False,AMD,NaN
68863,295960,R,2015-03-17,NaN,NaN,NaN,NaN,NaN,PD,5-156,R,NaN,False,False,False,False,AMD,NaN

## Match OCTs, visus, thickness 
- OCTs and thickness based on study date
- visus and OCTs on same date (NEVER after injection)

number of matches increased when not accurately merging on date with with timespa

In [ ]:
###### octs

In [58]:
merged = pd.merge(octs, visus, on=['patient_id', 'laterality', 'study_date'], how='outer') # keep all visus labels
print('Result: {} oct/visus pairs'.format(len(merged.dropna(subset=['oct_path', 'visual_acuity']))))

print('Merging {} octs with {} injections'.format(len(merged), len(injections)))#
merged = pd.merge(merged, injections, on=['study_date', 'patient_id', 'laterality'], how='outer') # keep all injections
print('Result: {} oct/visus/injections pairs'.format(len(merged.dropna(subset=['oct_path', 'visual_acuity', 'ICPML', 'ICPMK']))))

Result: 178717 oct/visus pairs
Merging 760047 octs with 315216 injections
Result: 30008 oct/visus/injections pairs

In [59]:
merged['thickness_path'] = np.nan

# make results columns nice
merged.loc[:,'oct?'] = ~merged['oct_path'].isna()
merged.loc[:,'visus?'] = ~merged['logMAR'].isna()
merged.loc[:,'thickness?'] = ~merged['thickness_path'].isna()
merged.loc[:,'fundus?'] = ~merged['fundus_path'].isna()

oct_measurements = merged.copy()
# clean up merged table
oct_measurements = oct_measurements.drop(columns=['visual_acuity_raw', 'logMAR_raw', 'visual_acuity_origin'])

In [60]:
disp_cols = ['patient_id', 'laterality', 'study_date', 'oct?', 'visus?', 'thickness?', 'fundus?']
oct_measurements[disp_cols]

        patient_id laterality study_date   oct?  visus?  thickness?  fundus?
0           363979          R 2018-01-29   True    True       False    False
1           363979          L 2018-01-29   True    True       False    False
2           350569          R 2017-03-06   True    True       False    False
3           350569          L 2017-03-06   True    True       False    False
4           185669          L 2014-12-09   True    True       False    False
...            ...        ...        ...    ...     ...         ...      ...
1013115     375294          R 2018-11-19  False   False       False    False
1013116     375374          R 2018-11-19  False   False       False    False
1013117     375414          R 2018-11-26  False   False       False    False
1013118     375579          R 2018-11-21  False   False       False    False
1013119     375651          R 2018-11-22  False   False       False    False

[1013120 rows x 7 columns]

In [61]:
# results statistics
# OCTs
mask = oct_measurements['oct?']
num = sum(mask)
pat = len(oct_measurements[mask].patient_id.unique())
print('OCTs: {} measurements from {} patients'.format(num, pat))

mask = (oct_measurements['oct?']) & (oct_measurements['visus?'])
num = sum(mask)
pat = len(oct_measurements[mask].patient_id.unique())
print('OCTs with va: {} measurements from {} patients'.format(num, pat))

OCTs: 213048 measurements from 34062 patients
OCTs with va: 179158 measurements from 29720 patients

## Prepare data for Times series modeling

### Limit oct measurements to longitudinal patients, add diagnosis

In [62]:
# merge diagnosis label to each patient instance (laterality + study date)
longitudinal_data = pd.merge(oct_measurements, diagnosis[['patient_id', 'laterality', 'diagnosis']], 
                             on=['patient_id', 'laterality'], how='inner')

In [63]:
longitudinal_data["MED"] = np.nan

### Create events table with injections and surgery dates

In [64]:
longitudinal_patients = diagnosis[['patient_id', 'laterality']].drop_duplicates(['patient_id', 'laterality'])

# add injections
events = pd.merge(longitudinal_patients, injections[['patient_id', 'laterality', 'study_date', 'ICPML']], 
                  on=['patient_id', 'laterality'], how='inner')

events.loc[:,'injection?'] = ~events['ICPML'].isna()

# add lens surgery data
lens_surgery = diagnosis[['patient_id', 'laterality', 'iol_date']].copy()
lens_surgery.rename(columns={'iol_date': 'study_date'}, inplace=True)
lens_surgery['iol?'] = ~lens_surgery.study_date.isna()
lens_surgery = lens_surgery[lens_surgery['iol?']]

lens_surgery.loc[:, "study_date"] = pd.to_datetime(lens_surgery.study_date)

# limit to longitudinal data
lens_surgery = pd.merge(longitudinal_patients, lens_surgery, on=['patient_id', 'laterality'], how='inner')

# add to events
events = pd.merge(events, lens_surgery, on=["laterality", "patient_id", "study_date"], how="left")

# we do not know medication at this point. Medications to be added
events["MED"] = np.nan

# drop non injection data and duplicates
# events = events.dropna(subset=["injection?"]).drop_duplicates(subset=["laterality", "patient_id", "study_date"])

### merge medication information

In [66]:
## load tables
med_pd = pd.read_csv(os.path.join(data_dir, "medications.csv"))
med_pd = med_pd[~med_pd.study_date.isin([-1])]

### pre process date columns
med_pd.loc[:, "study_date"] = pd.to_datetime(med_pd.study_date.astype(int).astype(str), format="%Y%m%d")
med_pd.loc[:, "DAT"] = pd.to_datetime(med_pd.DAT)
med_pd[["pseudo_id"]] = med_pd["pseudo_id"].astype(str)

events_med_pd = pd.merge(events, med_pd[["pseudo_id", "laterality", "DAT", "MED"]], 
         left_on=["patient_id", "laterality", "study_date"], 
         right_on=["pseudo_id", "laterality", "DAT"], 
         how="left")

columns_final = ["patient_id", "laterality", "study_date", "ICPML", "injection?", "iol?", "MED_y"]

events_med_pd = events_med_pd[columns_final].drop_duplicates()
events_med_pd.rename(columns={"MED_y": "MED"}, inplace=True)
print("Event & MED records: ", events_med_pd.shape[0])

Event & MED records:  34567

### save tables

In [67]:
if not os.path.exists(os.path.join(DATA_DIR, 'longitudinal_data')):
    os.makedirs(os.path.join(DATA_DIR, 'longitudinal_data'))
    
longitudinal_data.to_csv(os.path.join(DATA_DIR, 'longitudinal_data/longitudinal_data.csv'))
events_med_pd.to_csv(os.path.join(DATA_DIR, 'longitudinal_data/longitudinal_events.csv'))

#### get all patients with events before 2014-02-01

In [ ]:
# load naive patients
RAW_DIR = "/storage/groups/ml01/datasets/raw/2018_LMUAugenklinik_niklas.koehler"
longitudinal_dir = os.path.join(RAW_DIR, "joint_export/longitudinal_tables")

naive_list = pd.read_csv(os.path.join(longitudinal_dir, 'full_naive_list.csv'), index_col=0)
naive_patients = naive_list[naive_list.Naive.astype(int) == 1].patient_id.drop_duplicates().astype(str).tolist()

In [ ]:
events_before = events[events.study_date <= "2014-02-01"]
events_before = events_before[events_before.patient_id.isin(naive_patients)]
events_before_naive = events_before.sort_values(by="study_date").drop_duplicates(subset=["patient_id", 
                                                                                         "laterality"])  

rows_to_check = []
oct_dates = []
for row in events_before_naive.itertuples():
    patient = row[1]
    laterality = row[2]
    
    lrecord = longitudinal_data[(longitudinal_data.patient_id == f"{str(patient)}") & \
                                (longitudinal_data.laterality == f"{laterality}")]
    
    first_date_w_oct_and_logMAR = lrecord[lrecord.logMAR.isna()].dropna(subset=["oct_path"])
    
    first_date_w_oct_and_logMAR = first_date_w_oct_and_logMAR.sort_values(by=["study_date"])
    
    if first_date_w_oct_and_logMAR.size > 0:
        first_date_w_oct_and_logMAR = first_date_w_oct_and_logMAR.iloc[0].study_date

        if first_date_w_oct_and_logMAR < row[3]:
            rows_to_check.append(row)
            oct_dates.append(first_date_w_oct_and_logMAR)
            
    else:
        print(row)
              
to_check_va = pd.DataFrame(rows_to_check)[["patient_id","laterality","study_date"]]
to_check_va = to_check_va.rename(columns={"study_date": "first_injection_date"})
to_check_va["first_oct_date_registrered_wo_visual_acuity"] = oct_dates

to_check_va.to_csv(os.path.join(workspace_dir, 'joint_export/manual_visual_acuity_check.csv'))

In [ ]:
to_check_va